### ISSUE TITLE
Tutor - Release - 11-06-2019

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/tutor-js#2780]
Code freeze - QA: 10/25/2019 
RC Review meeting: 10/29/2019 
Code deploy - Staging: 10/31/2019
Code Release - Production: 11/06/2019

### Emergency Preparation 
- [x] Verify automated RDS backups completed successfully. 
- [x] Record existing tags for deployed repos 

#### Before Deployment Tasks
- [x]   stop unicorn and background workers before scheduler deployment (devops)
 
###### Only list the repos that are deployed for this release. 

- [x]  openstax/tutor-deployment @v23.0.5
- [x]  openstax/biglearn-api @v13.2.1
- [x]  openstax/biglearn-local-query @v10.2.0
- [x]  openstax/biglearn-scheduler @v10.3.2
- [x]  openstax/biglearn-sparfa-server @v3.1.0
- [x]  openstax/validation-deployment @v3.0.0
- [x]  openstax/exercises @v26.5.0
- [x]  openstax/tutor-js (exercises-js) @v26.0.6
- [x]  openstax/tutor-server @v26.0.0
- [x]  openstax/tutor-js @v26.0.6

###### Only list the repos that are deployed for this release. 

- [x]  openstax/tutor-deployment @v23.0.5
- [x]  openstax/exercises @v26.5.0
- [x]  openstax/tutor-js (exercises-js) @v26.0.6
- [x]  openstax/tutor-js @v26.0.6

###### Only list the repos that are deployed for this release. 

- [x]  openstax/tutor-deployment @v23.0.5
- [x]  openstax/tutor-js @v26.0.6

### Migrations
- [x] Yes 
- [ ] No 

#### After Deployment Tasks
- [ ]  Reimport 5 in-use books (ecosystem import) to response validator 
- [ ]  Might need to restart response validator deployment

### Emergency (Only filled in if there is a full rollback) 
- [ ] Rename RDS instance of app to be rolled back to `<name>-failed-<date>`
- [ ] Restore RDS snapshot to `<name>`
- [ ] Set Security Group of new RDS instance to match the original instance
- [ ] Deploy previous tags to restore old code. 

## End DevOps Production Deploy
-----------------------------------------------------------------------------------------
### Versions being tested:

On Staging Environment: *Passed*
###### Put an X for the repos *not* going out

- [ ]  openstax/tutor-deployment @v23.0.5
- [ ]  openstax/accounts @ X
- [ ]  openstax/biglearn-api @v13.2.1
- [ ]  openstax/biglearn-local-query @v10.2.0
- [ ]  openstax/biglearn-scheduler @v10.3.2
- [ ]  openstax/biglearn-sparfa-server @v3.1.0
- [ ]  openstax/validation-deployment @v3.0.0
- [ ]  openstax/exercises @v26.5.0
- [ ]  openstax/tutor-js (exercises-js) @v26.0.6
- [ ]  openstax/tutor-server @v26.0.0
- [ ]  openstax/tutor-js @v26.0.6
-----------------------------------------------------------------------------------------

On QA Environment: *Passed*
###### Put an X for the repos *not* going out

- [ ]  openstax/tutor-deployment @v23.0.4
- [ ]  openstax/accounts @ X
- [ ]  openstax/biglearn-api @v13.2.1
- [ ]  openstax/biglearn-local-query @v10.2.0
- [ ]  openstax/biglearn-scheduler @v10.3.2
- [ ]  openstax/biglearn-sparfa-server @v3.1.0
- [ ]  openstax/validation-deployment @v3.0.0
- [ ]  openstax/exercises @v26.5.0
- [ ]  openstax/tutor-js (exercises-js) @v26.0.5
- [ ]  openstax/tutor-server @v26.0.0
- [ ]  openstax/tutor-js @v26.0.5
-----------------------------------------------------------------------------------------

**Comment by scb6** [comment]
existing tags: 

```
tutor-server            e4932d630973122aef43989ee378848840144b35  v24.1.1  2019-10-09T09:51:11       
tutor-js                0908d02fd3495270fdcbb6de7fa14472858928fc  v24.1.6  2019-10-07T10:25:05       
exercises               3cf48ab01618e36ab450fd1364f099eb5a5e4a60  v26.4.1  2019-10-09T09:39:04       
exercises-js            0908d02fd3495270fdcbb6de7fa14472858928fc  v24.1.6  2019-10-09T09:36:27       
accounts                1ed108298af5058a369e2cf05314210649d4b7b6  v2.5.1   2019-10-09T09:00:11       
biglearn-api            88a83d746ea387cba0de28382be1b801533f2b78  v13.1.0  2019-09-11T08:50:59       
biglearn-local-query    c2bb0de1ec496c061f56c0f59b62bd05eefa47c4  v10.1.1  2019-10-09T09:31:43       
biglearn-scheduler      6be1b622712f108ea4c74865936f66f38a0c4cb8  v10.2.0  2019-10-23T08:39:53       
biglearn-sparfa-server  ce203d67012b38bb1a4b8aad64acb1afca35344a  v3.0.0   2019-10-23T08:48:04       
tutor-deployment        b254295984bef86c60ad58ae6e330e0db47d7de2  v22.0.0  2019-10-23T08:49:37 ```
