### ISSUE TITLE
Tutor - Release - 12-04-2019

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/tutor-js#2824]
Code freeze - QA: 11/22/2019 
RC Review meeting: 11/26/2019 
Code deploy - Staging: 11/28/2019
Code Release - Production: 12/04/2019

### Emergency Preparation 
- [ ] Verify automated RDS backups completed successfully. 
- [ ] Record existing tags for deployed repos 

#### Before Deployment Tasks
- [ ]  tasks
 
###### Only list the repos that are deployed for this release. 

- [x]  openstax/tutor-deployment @ v24.0.0
- [x]  openstax/accounts @ v2.5.4
- [x]  openstax/biglearn-sparfa-server @ v3.3.0
- [x]  openstax/exercises @ v26.7.0
- [x]  openstax/tutor-js (exercises-js) @ v28.0.2
- [x]  openstax/tutor-server @ v28.0.1
- [x]  openstax/tutor-js @ v28.0.2

###### Only list the repos that are deployed for this release. 

- [x]  openstax/tutor-deployment @ v24.0.0
- [x]  openstax/accounts @ v2.5.4
- [x]  openstax/exercises @ v26.7.0
- [x]  openstax/tutor-js (exercises-js) @ v28.0.2
- [x]  openstax/tutor-js @ v28.0.2

###### Only list the repos that are deployed for this release. 

- [x]  openstax/tutor-deployment @ v24.0.0
- [x]  openstax/accounts @ v2.5.4
- [x]  openstax/tutor-js @ v28.0.2

### Migrations
- [x] Yes 
- [ ] No 

#### After Deployment Tasks
- [ ] Make sure the background migration runs, since it failed the last time on production 

### Emergency (Only filled in if there is a full rollback) 
- [ ] Rename RDS instance of app to be rolled back to `<name>-failed-<date>`
- [ ] Restore RDS snapshot to `<name>`
- [ ] Set Security Group of new RDS instance to match the original instance
- [ ] Deploy previous tags to restore old code. 

## End DevOps Production Deploy
-----------------------------------------------------------------------------------------
### Versions being tested:

On Staging Environment: *Status*
###### Put an X for the repos *not* going out

- [ ]  openstax/tutor-deployment @ v24.0.0
- [ ]  openstax/accounts @ v2.5.4
- [ ]  openstax/biglearn-api @ X
- [ ]  openstax/biglearn-local-query @ X
- [ ]  openstax/biglearn-scheduler @ X
- [ ]  openstax/biglearn-sparfa-server @ v3.3.0
- [ ]  openstax/validatior-deployment @ X
- [ ]  openstax/exercises @ v26.7.0
- [ ]  openstax/tutor-js (exercises-js) @ v28.0.2
- [ ]  openstax/tutor-server @ v28.0.1
- [ ]  openstax/tutor-js @ v28.0.2
-----------------------------------------------------------------------------------------

On QA Environment: *Passed*
###### Put an X for the repos *not* going out

- [ ]  openstax/tutor-deployment @ v24.0.0
- [ ]  openstax/accounts @ v2.5.4
- [ ]  openstax/biglearn-api @ X
- [ ]  openstax/biglearn-local-query @ X
- [ ]  openstax/biglearn-scheduler @ X
- [ ]  openstax/biglearn-sparfa-server @ v3.3.0
- [ ]  openstax/validatior-deployment @ X
- [ ]  openstax/exercises @ v26.7.0
- [ ]  openstax/tutor-js (exercises-js) @ v28.0.2
- [ ]  openstax/tutor-server @ v28.0.1
- [ ]  openstax/tutor-js @ v28.0.2
-----------------------------------------------------------------------------------------

**Comment by dtwilliamson** [comment]
previous tags:
tutor-deployment v23.1.1
accounts v2.5.3
biglearn-sparfa-server v3.2.0
exercises v26.6.0
exercises-js v27.0.2
tutor-server v27.0.5
tutor-js v27.0.2
