### ISSUE TITLE
Tutor - Release - 04/08/2020

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/tutor-js#2944]
Code freeze - QA: 3/27/2020
RC Review meeting: 4/2/2020
Code deploy - Staging: 4/3/2020
Code Release - Production: 04/08/2020

### Emergency Preparation 
- [ ] Verify automated RDS backups completed successfully. 
- [ ] Record existing tags for deployed repos 

#### Before Deployment Tasks
- [ ]  Task
 
###### Only list the repos that are deployed for this release. 

- [x]  openstax/tutor-deployment @ v27.0.0
- [x]  openstax/accounts @ v3.4.2
- [x]  openstax/exercises @ v26.10.1
- [x]  openstax/tutor-js (exercises-js) @ v33.0.0
- [x]  openstax/tutor-server @ v33.0.3
- [x]  openstax/tutor-js @ v33.0.0

###### Only list the repos that are deployed for this release. 

- [x]  openstax/tutor-deployment @ v27.0.0
- [x]  openstax/accounts @ v3.4.2
- [ ]  openstax/exercises @ v26.10.1
- [ ]  openstax/tutor-js (exercises-js) @ v33.0.0
- [x]  openstax/tutor-server @ v33.0.3
- [x]  openstax/tutor-js @ v33.0.0

###### Only list the repos that are deployed for this release. 

- [x]  openstax/tutor-deployment @ v27.0.0
- [x]  openstax/accounts @ v3.4.2
- [x]  openstax/tutor-server @ v33.0.3
- [x]  openstax/tutor-js @ v33.0.0

### Migrations
- [x] Yes 
- [ ] No 

### After Deployment Tasks
- [ ] Task

### Emergency (Only filled in if there is a full rollback) 
- [ ] Rename RDS instance of app to be rolled back to `<name>-failed-<date>`
- [ ] Restore RDS snapshot to `<name>`
- [ ] Set Security Group of new RDS instance to match the original instance
- [ ] Deploy previous tags to restore old code. 

## End DevOps Production Deploy
-----------------------------------------------------------------------------------------
### Versions being tested:

On Staging Environment: *Passed*
###### Put an X for the repos *not* going out

- [ ]  openstax/tutor-deployment @ v27.0.0
- [ ]  openstax/accounts @ v3.4.2
- [ ]  openstax/biglearn-api @ X
- [ ]  openstax/biglearn-local-query @ X
- [ ]  openstax/biglearn-scheduler @ X
- [ ]  openstax/biglearn-sparfa-server @ X
- [ ]  openstax/exercises @ v26.10.1
- [ ]  openstax/tutor-js (exercises-js) @ v33.0.0
- [ ]  openstax/tutor-server @ v33.0.3
- [ ]  openstax/tutor-js @ v33.0.0
- [ ]  openstax/validation-server @ X
- [ ]  openstax/validation-deployment @ X
-----------------------------------------------------------------------------------------

On QA Environment: *Passed*
###### Put an X for the repos *not* going out

- [ ]  openstax/tutor-deployment @ v27.0.0
- [ ]  openstax/accounts @ v3.4.1
- [ ]  openstax/biglearn-api @ X
- [ ]  openstax/biglearn-local-query @ X
- [ ]  openstax/biglearn-scheduler @ X
- [ ]  openstax/biglearn-sparfa-server @ X
- [ ]  openstax/exercises @ v26.10.1
- [ ]  openstax/tutor-js (exercises-js) @ v33.0.0
- [ ]  openstax/tutor-server @ v33.0.3
- [ ]  openstax/tutor-js @ v33.0.0
- [ ]  openstax/validation-server @ X
- [ ]  openstax/validation-deployment @ X
-----------------------------------------------------------------------------------------
