### ISSUE TITLE
Tutor - Release - 5/20/2020

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/tutor-js#2985]
Code freeze - QA: 5/8/2020
RC Review meeting: 5/14/2020
Code deploy - Staging: 5/15/2020
Code Release - Production: 5/20/2020

### Emergency Preparation 
- [ ] Verify automated RDS backups completed successfully. 
- [ ] Record existing tags for deployed repos 

#### Before Deployment Tasks
- [ ]  Task
 
###### Only list the repos that are deployed for this release. 

- [ ]  openstax/tutor-deployment @
- [ ]  openstax/accounts @
- [ ]  openstax/biglearn-api @
- [ ]  openstax/biglearn-local-query @
- [ ]  openstax/biglearn-scheduler @
- [ ]  openstax/biglearn-sparfa-server @
- [ ]  openstax/exercises @
- [ ]  openstax/tutor-js (exercises-js) @
- [ ]  openstax/tutor-server @
- [ ]  openstax/tutor-js @
- [ ]  openstax/validation-server @
- [ ]  openstax/validation-deployment @

###### Only list the repos that are deployed for this release. 

- [ ]  openstax/tutor-deployment @
- [ ]  openstax/accounts @
- [ ]  openstax/biglearn-api @
- [ ]  openstax/biglearn-local-query @
- [ ]  openstax/biglearn-scheduler @
- [ ]  openstax/biglearn-sparfa-server @
- [ ]  openstax/exercises @
- [ ]  openstax/tutor-js (exercises-js) @
- [ ]  openstax/tutor-server @
- [ ]  openstax/tutor-js @

###### Only list the repos that are deployed for this release. 

- [ ]  openstax/tutor-deployment @
- [ ]  openstax/accounts @
- [ ]  openstax/tutor-server @
- [ ]  openstax/tutor-js @

### Migrations
- [ ] Yes 
- [ ] No 

### After Deployment Tasks
- [ ] Task

### Emergency (Only filled in if there is a full rollback) 
- [ ] Rename RDS instance of app to be rolled back to `<name>-failed-<date>`
- [ ] Restore RDS snapshot to `<name>`
- [ ] Set Security Group of new RDS instance to match the original instance
- [ ] Deploy previous tags to restore old code. 

## End DevOps Production Deploy
-----------------------------------------------------------------------------------------
### Versions being tested:

On Staging Environment: *Status*
###### Put an X for the repos *not* going out

- [ ]  openstax/tutor-deployment @
- [ ]  openstax/accounts @
- [ ]  openstax/biglearn-api @
- [ ]  openstax/biglearn-local-query @
- [ ]  openstax/biglearn-scheduler @
- [ ]  openstax/biglearn-sparfa-server @
- [ ]  openstax/exercises @
- [ ]  openstax/tutor-js (exercises-js) @
- [ ]  openstax/tutor-server @
- [ ]  openstax/tutor-js @
- [ ]  openstax/validation-server @
- [ ]  openstax/validation-deployment @
-----------------------------------------------------------------------------------------

On QA Environment: *Status*
###### Put an X for the repos *not* going out

- [ ]  openstax/tutor-deployment @
- [ ]  openstax/accounts @
- [ ]  openstax/biglearn-api @
- [ ]  openstax/biglearn-local-query @
- [ ]  openstax/biglearn-scheduler @
- [ ]  openstax/biglearn-sparfa-server @
- [ ]  openstax/exercises @
- [ ]  openstax/tutor-js (exercises-js) @
- [ ]  openstax/tutor-server @
- [ ]  openstax/tutor-js @
- [ ]  openstax/validation-server @
- [ ]  openstax/validation-deployment @
-----------------------------------------------------------------------------------------

**Comment by meeragovindaraju** [comment]
Skipping this release to accommodate Glick + WRM release/testing
