### ISSUE TITLE
Tutor Release - 3/10/2021

### ISSUE THREAD

**Issue by Brooke-Fail** [openstax/tutor-js#3476]
Code freeze - QA: n3/1/2021
RC Review meeting:  3/4/2021
Code deploy - Staging: 3/4/2021
Code Release - Production: 3/10/2021

### Emergency Preparation 
- [ ] Verify automated RDS backups completed successfully. 
- [ ] Record existing tags for deployed repos 

#### Before Deployment Tasks
- [ ]  
 
###### Only list the repos that are deployed for this release. 
- [ ]  openstax/tutor-deployment @ 
- [ ]  openstax/accounts @  
- [ ]  openstax/exercises @ 
- [ ]  openstax/tutor-js (exercises-js) @ 
- [ ]  openstax/tutor-server @  
- [ ]  openstax/tutor-js @ 
- [ ]  openstax/response-validator @ 
- [ ] openstax/validator-deployment @ 
----------------------------------------------

###### Only list the repos that are deployed for this release. 

- [ ]  openstax/tutor-deployment @
- [ ]  openstax/accounts @
- [ ]  openstax/exercises @
- [ ]  openstax/tutor-js (exercises-js) @
- [ ]  openstax/tutor-server @
- [ ]  openstax/tutor-js @

###### Only list the repos that are deployed for this release. 

- [ ]  openstax/tutor-deployment @
- [ ]  openstax/accounts @
- [ ]  openstax/tutor-server @
- [ ]  openstax/tutor-js @

### Migrations
- [ ] Yes 
- [ ] No 

### After Deployment Tasks
- [ ] 

### Emergency (Only filled in if there is a full rollback) 
- [ ] Rename RDS instance of app to be rolled back to `<name>-failed-<date>`
- [ ] Restore RDS snapshot to `<name>`
- [ ] Set Security Group of new RDS instance to match the original instance
- [ ] Deploy previous tags to restore old code. 

## End DevOps Production Deploy
-----------------------------------------------------------------------------------------
### Versions being tested:

On Staging Environment: *Status*
###### Put an X for the repos *not* going out

- [ ]  openstax/tutor-deployment @ X
- [ ]  openstax/accounts @  X
- [ ]  openstax/exercises @ 
- [ ]  openstax/tutor-js (exercises-js) @ X
- [ ]  openstax/tutor-server @  X
- [ ]  openstax/tutor-js @ X
- [ ]  openstax/response-validator @ X
- [ ] openstax/validator-deployment @ X
-----------------------------------------------------------------------------------------

On QA Environment: *Status*
###### Put an X for the repos *not* going out

- [ ]  openstax/tutor-deployment @ X
- [ ]  openstax/accounts @  X
- [ ]  openstax/exercises @ X
- [ ]  openstax/tutor-js (exercises-js) @ X
- [ ]  openstax/tutor-server @  X
- [ ]  openstax/tutor-js @  X
- [ ]  openstax/response-validator @ X
- [ ] openstax/validator-deployment @ X
-----------------------------------------------------------------------------------------

**Comment by Brooke-Fail** [comment]
All cards in this release have been verified and closed.
