### ISSUE TITLE
Tutor Release - 1/19/2022

### ISSUE THREAD

**Issue by Brooke-Fail** [openstax/tutor-js#3850]
Code freeze - QA: n/a
RC Review meeting:  n/a
Code deploy - Staging: 1/14/2022
Code Release - Production: 1/19/2022

### Emergency Preparation 
- [ ] Verify automated RDS backups completed successfully. 
- [ ] Record existing tags for deployed repos 

#### Before Deployment Tasks
- [ ]  
 
###### Only list the repos that are deployed for this release. 
- [ ]  openstax/tutor-deployment @ 
- [ ]  openstax/accounts @  
- [ ]  openstax/exercises @ 
- [ ]  openstax/tutor-js (exercises-js) @ 
- [ ]  openstax/tutor-server @  
- [ ]  openstax/tutor-js @ 
- [ ]  openstax/response-validator @ 
- [ ] openstax/validator-deployment @ 
----------------------------------------------

###### Only list the repos that are deployed for this release. 

- [ ]  openstax/tutor-deployment @
- [ ]  openstax/accounts @
- [ ]  openstax/exercises @
- [ ]  openstax/tutor-js (exercises-js) @
- [ ]  openstax/tutor-server @
- [ ]  openstax/tutor-js @

###### Only list the repos that are deployed for this release. 

- [ ]  openstax/tutor-deployment @
- [ ]  openstax/accounts @
- [ ]  openstax/tutor-server @
- [ ]  openstax/tutor-js @

### Migrations
- [ ] Yes 
- [ ] No 

### After Deployment Tasks
- [ ] 

### Emergency (Only filled in if there is a full rollback) 
- [ ] Rename RDS instance of app to be rolled back to `<name>-failed-<date>`
- [ ] Restore RDS snapshot to `<name>`
- [ ] Set Security Group of new RDS instance to match the original instance
- [ ] Deploy previous tags to restore old code. 

## End DevOps Production Deploy
-----------------------------------------------------------------------------------------
### Versions being tested:

On Staging Environment: *Status*
###### Put an X for the repos *not* going out

- [ ]  openstax/tutor-deployment @ v44.0.0
- [ ]  openstax/accounts @  X
- [ ]  openstax/exercises @ v37.2.0
- [ ]  openstax/tutor-js (exercises-js) @ v60.1.0
- [ ]  openstax/tutor-server @ v60.1.0
- [ ]  openstax/tutor-js @ v60.1.0
- [ ]  openstax/response-validator @ X
- [ ] openstax/validator-deployment @ X
-----------------------------------------------------------------------------------------

On QA Environment: *Testing*
###### Put an X for the repos *not* going out

- [ ]  openstax/tutor-deployment @ v43.5.3
- [ ]  openstax/accounts @  X
- [ ]  openstax/exercises @ v37.1.2
- [ ]  openstax/tutor-js (exercises-js) @ v60.0.0
- [ ]  openstax/tutor-server @ v60.0.0
- [ ]  openstax/tutor-js @ v60.0.0
- [ ]  openstax/response-validator @ X
- [ ] openstax/validator-deployment @ X
-----------------------------------------------------------------------------------------
