### ISSUE TITLE
Selenium: Suggestion for common names for screen commands

### ISSUE THREAD

**Issue by philschatz** [openstax/tutor-js#987]
Here's a _suggestion_ for predictable names for commands that can be done on all the screens in tutor. I went through all the screens and tried to list off all the things a person can click. What do folks think?

/cc @openstax/tutor-fe @openstax/test 

# TODO

- [ ] add these to a documentation file

# Teacher

These are largely teacher-specific screens

## Calendar

`assignmentType`: `'HOMEWORK' | 'READING' | 'EXTERNAL' | 'EVENT'`
`relativeDate`: `'TODAY' | 'TOMORROW' | 'FIRST'`

- [x] `goToBook()`
- [x] `goToForecast()`
- [x] `goToScores()`
- [ ] `goToAddByType(assignmentType)`
- [ ] `goToAddByTypeFromNow(assignmentType, relativeDate)`
- [ ] `goToPreviousMonth()`
- [ ] `goToNextMonth()`
- [x] `goToOpenByTitle(title)`
- [ ] `goToEditByTitle(title)`
- [ ] `goToReviewByTitle(title)`

### Popup

- [ ] `selectPeriodByIndex(num)`
- [ ] `selectPeriodByTitle(title)`
- [x] `goToReview()`
- [x] `goToEdit()`

## CC-Dashboard

- [x] `goToScores()`
- [x] `goToBook()`
- [ ] `selectPeriodByIndex(num)`
- [ ] `selectPeriodByTitle(title)`

## Builder

- [x] `edit({settings})`

## Scores

- [ ] `selectDisplayAsNumber()`
- [ ] `selectDisplayAsPercent()`
- [ ] `selectBasedOnPossible()`
- [ ] `selectBasedOnAttempted()`
- [ ] `selectPeriodByIndex(num)`
- [ ] `selectPeriodByTitle(title)`
- [ ] `sortName()`
- [ ] `goToAssignmentByIndexes(row, column)`
- [ ] `downloadExport()`

CC Commands:

- [ ] `sortAssignmentScoreByIndex(index)`
- [ ] `sortAssignmentCompletedByIndex(index)`
- [ ] `sortAssignmentScoreByTitle(title)`

HS Commands:

- [ ] `goToForecastByName(studentName)`
- [ ] `goToReviewByIndex(index)`
- [ ] `goToReviewByTitle(title)`

### Review

`stepStatus`: `'ANY' | 'UNSTARTED' | 'COMPLETED' | 'CORRECT' | 'INCORRECT'`

- [ ] `goToBack()`
- [ ] `selectPeriodByIndex(num)`
- [ ] `selectPeriodByTitle(title)`
- [ ] `selectStepByIndex(index)`
- [ ] `selectStepByStatus(stepStatus)`
- [ ] `getExerciseByIndex(index)`

## Roster

- [ ] `renameCourse(name)`
- [ ] `removeInstructorByIndex(index)`
- [ ] `removeInstructorByName(firstName, lastName=null)`
- [ ] `selectPeriodByIndex(num)`
- [ ] `selectPeriodByTitle(title)`
- [ ] `addPeriod(title)`
- [ ] `renamePeriod(title)`
- [ ] `removePeriod()`
- [ ] `changePeriodByName(firstName, lastName=null)`
- [ ] `removeStudentByIndex(index)`
- [ ] `removeStudentByName(firstName, lastName=null)`

# Student

These are largely student-specific screens

## Dashboard

- [ ] `showPastWork()`
- [ ] `showCurrentWork()`
- [ ] `goToPracticeByIndex(index)`
- [ ] `goToPracticeBySection('4.3')`
- [ ] `goToPracticeWeakest()`
- [ ] `goToForecast()`
- [ ] `goToBook()`

- [ ] `goToAssignmentByIndexe(index)`
- [ ] `goToAssignmentByType(assignmentType)`
- [ ] `goToAssignmentByTitle(title)`

# Both

These screens do the same thing for teachers and students

## CourseSelect

`courseType`: `'ANY' | 'BIOLOGY' | 'PHYSICS' | 'CONCEPT_COACH'`

- [x] `goToByType(courseType)`
- [x] `goToByTitle(title)`

## User (the navbar on the top plus login/logout)

- [x] `goToHome()`
- [ ] `goToCourseHome()`
- [ ] `goToDashboard()`
- [ ] `goToForecast()`
- [ ] `goToBook()`
- [ ] `goToAccount()`
- [ ] `goToHelp()`
- [ ] `goToLogout()`
- [ ] `openHamburgerMenu()`
- [ ] `toggleHamburgerMenu()`

Teacher-only:

- [ ] `goToScores()`
- [ ] `goToRoster()`

## Forecast

Teacher-only:

- [ ] `goToBack()`
- [ ] `selectPeriodByIndex(num)`
- [ ] `selectPeriodByTitle(title)`

Student-only:

- [ ] `goToBack()`
- [ ] `goToPracticeByIndex(index)`
- [ ] `goToPracticeBySection('4.3')`

## Task

- [x] `continue()`
- [ ] `selectStepByIndex(index)`
- [ ] `selectStepByStatus(stepStatus)`
- [ ] `selectCompletionStep()`

### Exercise

Teacher-only:

- [ ] `toggleFreeResponse()`

Student-only:

- [ ] `enterFreeResponse(msg=null)`
- [ ] `selectAnswerByIndex(index)`

**Comment by gregfitch** [comment]
Any reason for 'go...' instead of 'goto...'?

**Comment by philschatz** [comment]
Ah, I was wondering what `goBack()` would turn into. and what would the casing be? (ie `gotoCourseHome()` or `goToCourseHome()` )

**Comment by gregfitch** [comment]
Well, I spend most of my time in Python nowadays, so 'go_to_...' is the norm  :)
The latter would be more likely ( http://c2.com/cgi/wiki?LowerCamelCase ).

**Comment by philschatz** [comment]
so, are you suggesting special-casing the naming of `goBack()` or suggesting it should be `goToBack()`? I updated the Issue body to use `goTo*`.

Also, any thoughts on the other names?

**Comment by gregfitch** [comment]
I try to keep a natural language flow in the naming so 'goBack' is fine, except what case does it serve? It seems to be ambiguous in many cases whereas 'goToDashboard' or 'goToHome' make it clear what is expected to happen.

If 'goBack' is there to test the back button and the history, you may want to expand the function text.

**Comment by philschatz** [comment]
It's just to test the "Back to X" button (sometimes it's back to Scores, sometimes it's back to Calendar, depending on where you came from) So, depending on how you got to the screen, the button goes back to a different place.

**Comment by philschatz** [comment]
Marking this as complete because several of these method names were added as comments to the helper files
